services:
  - type: web
    name: summarizer-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HF_TOKEN
        value: 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
